apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
        containers:
        - name: myapp
          image: avaldominos/python-app:latest # <-- CircleCI will update this tag
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5000